import type { Metadata } from "next";
import { Lato, Fira_Code  } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const lato = Lato({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-lato'
});

const fira_code = Fira_Code({
  subsets: ['latin'],
  variable: '--font-firacode'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fira_code.variable} ${lato.variable}`}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
